# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8dab9c03c105836d73a3ebe42fa48b9633934fde0047016227fa77162514116d83fa31ba182dff49bfe782285eb9deff1d36347bc9e0dd33cfef866a5b63d2d

test:
  secret_key_base: 168ec40c82318e522a123bd4d53340ca3096de715ade315866d5e0733e5d13256f2f9dc0e68705ab1e947efabdcc7ad1ffc20855c5d1714a4c2e73808d852c62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
